- browser/imap.py
- browser/views.py
- engine/youps.py
- http_handler/__init__.py
- schema/__init__.py
- schema/models.py
- schema/youps.py
- smtp_handler/main.py
- smtp_handler/management/commands/mailbot.py
- smtp_handler/management/commands/polling.py
- smtp_handler/management/commands/youps_test.py
> Add Message & thread entity

- Makefile
- browser/imap.py
- browser/models/event.py
- browser/models/event_data.py
- browser/models/folder.py
- browser/models/mailbox.py
- browser/models/message.py
- browser/sandbox.py
- engine/youps.py
- http_handler/settings.py
- http_handler/tasks.py
Keeping track of known bugs here
- now using capabilites to determine which label method to use.
1. When should we update our cache. For example if we do something like `message.mark_read()` and then say `message.is_read()` the marking may succeed but the `is_read` will return False. This is cause we base `is_read` on the flags in the database and `mark_read` only updates the server. Maybe we want to update the database as well.
2. What kind of aliases do we want. Right now I only have `[add,remove]_label` another example is `to` used to be `recipients`.
> Making newmessage work

- http_handler/tasks.py
will close https://github.com/soyapark/murmur/issues/52
> Celery lock

- browser/templates/youps/login_email.html
- browser/views.py
- engine/youps.py
- http_handler/static/css/youps/style.css
- http_handler/static/javascript/youps/login_imap.js
will close https://github.com/soyapark/murmur/issues/21
> folder selector UI and save it to database

- http_handler/static/css/youps/style.css
- http_handler/static/javascript/youps/login_imap.js
it is a duplicate of https://github.com/soyapark/murmur/pull/24.
will close https://github.com/soyapark/murmur/issues/23
> Ui namespace

- Makefile
- docker-compose.yml
- http_handler/urls.py
- requirements.docker.txt
- scripts/new_database.sh
- scripts/new_database_unsafe.sh
- youps_db_sql
No longer reseting database by default and have some nice commands in the makefile.
> Making Docker Nicer!

- browser/imap.py
- browser/models/contact.py
- browser/models/event.py
- browser/models/folder.py
- browser/models/message.py
- browser/sandbox.py
- browser/templates/youps/login_email.html
- http_handler/static/css/youps/style.css
- http_handler/static/javascript/youps/login_imap.js
- http_handler/tasks.py
- schema/youps.py
- smtp_handler/management/commands/mailbot.py
- smtp_handler/utils.py
1. implement Message object inspector at console UI. Partially address https://github.com/soyapark/murmur/issues/7
2. Change message.sender and from_ to single foreign key
3. Re-arrange event handling logic at sandbox: it fetches events first and log so it prints logs for users even when they don't have any mode running.
> Message object inspector at console

- browser/templates/youps/docs.html
- http_handler/static/css/youps/style.css
- http_handler/static/javascript/youps/sidebar.js
Added levels to the sidebar.
*   - Divs to be added to the sidebar need the class `add-sidebar`
*   - Another class specifies the level [`header`, `sub-header`, `value`]
*      - Each level will fall into the list of the last higher level
*      - `header` and `sub-header` use the innerHTML
*      - `value` uses the id of the div
> New sidebar

- browser/templates/youps/docs.html
- http_handler/static/css/youps/style.css
> bug(sidebar): fix safari padding

- browser/models/event_data.py
- browser/models/folder.py
- browser/models/mailbox.py
- browser/models/message.py
- browser/sandbox.py
- browser/templates/youps/login_email.html
- browser/views.py
- engine/youps.py
- http_handler/static/css/youps/style.css
- http_handler/static/javascript/youps/login_imap.js
- http_handler/tasks.py
- schema/__init__.py
- schema/youps.py
- smtp_handler/management/commands/cron_task.py
- smtp_handler/management/commands/youps_test.py
Now YoUPS supports scheduled message arrival events.
> Create new event_data type - NewMessageDataSceduled

- browser/models/message.py
- browser/sandbox.py
- browser/templates/youps/login_email.html
- http_handler/static/javascript/youps/login_imap.js
close https://github.com/soyapark/murmur/issues/101
> Ui paging log

- browser/models/event_data.py
- browser/models/folder.py
- browser/sandbox.py
> fixed missing from field and renamed NewMessage event

- browser/sandbox.py
- browser/templates/youps/login_email.html
- engine/models/contact.py
- engine/models/message.py
- engine/youps.py
- http_handler/static/css/youps/style.css
- http_handler/static/javascript/youps/login_imap.js
Enable simulations on new message event so users can see the result as soon as they save it. Parts of #87
> Instant debugging

- browser/templates/youps/login_email.html
- http_handler/static/css/youps/style.css
- http_handler/static/javascript/youps/login_imap.js
> UI - Fix dup tabs and mode dropdown

- browser/templates/youps/docs.html
- browser/templates/youps/login_email.html
- http_handler/static/css/youps/style.css
- http_handler/static/javascript/youps/login_imap.js
> Fix minor UI bugs

- browser/templates/youps/login_email.html
Uses the following script to confirm reloads:
```
<script>
window.onbeforeunload = function(event)
{
return confirm("Confirm refresh");
};
</script>
```
> feat(email_login): prevent unwanted reload

- browser/sandbox.py
- engine/youps.py
- http_handler/static/javascript/youps/login_imap.js
> Fetching message raw data after interpret()

- browser/sandbox.py
- browser/templates/youps/about.html
- browser/templates/youps/base.html
- browser/templates/youps/docs.html
- browser/templates/youps/login_email.html
- browser/views.py
- engine/models/contact.py
- engine/models/folder.py
- engine/youps.py
- http_handler/static/javascript/youps/login_imap.js
close #150 
close #143 
close #9 
close #135
> Calendar docs

- browser/imap.py
- browser/sandbox.py
- engine/models/message.py
- http_handler/static/javascript/youps/login_imap.js
- smtp_handler/main.py
> Shortcut log

- browser/sandbox.py
- browser/sandbox_helpers.py
- engine/models/mailbox.py
- engine/models/thread.py
- engine/youps.py
- smtp_handler/main.py
- smtp_handler/management/commands/mailbot.py
this fixes the stdout bug. rewrote half of sandbox still have to work on interpret but i factored out simulate.
> Rewrite sandbox

- Makefile
- engine/models/contact.py
- engine/models/folder.py
- http_handler/settings.py
- schema/youps.py
- scripts/new_database.sh
- scripts/new_database_unsafe.sh
- scripts/reset_user.sh
contact.name now returns the most common alias
fixes the issue where each contact would be associated with only the most recent name
> contacts can now have more than one alias

- http_handler/settings.py
- registration/models.py
- requirements.docker.txt
- scripts/new_database_unsafe.sh
We no longer use south (migration program) and now we use django native db migrations!
Test on dev server and it integrates well without any conflict
Related to https://github.com/haystack/YouPS/issues/178
> Upgrade django 1 7

- browser/templates/youps/login_email.html
- browser/views.py
- engine/youps.py
- schema/youps.py
> Use autofield for EmailRule ID

- Dockerfile
- Makefile
- config/settings.py
- docker-compose.yml
- http_handler/settings.py
- registration/models.py
- requirements.docker.txt
- smtp_handler/main.py
also fixed docker python2 upgrade to debian buster bugs
> fixed account activation email, 
